# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_new_entry_db.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_entry_db(object):
    def setupUi(self, new_entry_db):
        new_entry_db.setObjectName("new_entry_db")
        new_entry_db.resize(239, 250)
        new_entry_db.setMinimumSize(QtCore.QSize(239, 250))
        new_entry_db.setMaximumSize(QtCore.QSize(239, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("new_data_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        new_entry_db.setWindowIcon(icon)
        new_entry_db.setStyleSheet("QLabel {\n"
"    background-color: rgba(225, 225, 240, 10); /* Цвет фона с прозрачностью */\n"
"    color: #333;\n"
"    font: 75 10pt \"Courier\";\n"
"    border-radius: 7px; /* Скругление углов */\n"
"}\n"
"/* Загальний стиль вікна */\n"
"QWidget {\n"
"    background-color: rgba(225, 225, 240, 150); /* Космічно-синій фон */\n"
"}\n"
"QLineEdit{\n"
"    background-color: rgba(225, 225, 240, 150);\n"
"    color: #333;\n"
"    font: 75 10pt \"Courier\";\n"
"     border-radius: 7px; /* Скругление углов */\n"
"}\n"
"/* Стили для QTextEdit */\n"
"QTextEdit {\n"
"    background-color: rgba(225, 225, 240, 150); /* Цвет фона с прозрачностью */\n"
"    color: #333;\n"
"    font: 75 10pt \"Courier\";\n"
"    margin: 10px; \n"
"    border: 2px solid #aaa; /* Граница QTextEdit */\n"
"    border-radius: 7px; /* Скругление углов */\n"
"    padding: 10px; /* Внутренний отступ */\n"
"}\n"
"\n"
"QTextEdit::selection {\n"
"    background-color: #B4D5FF; /* Цвет выделенного текста */\n"
"    color: black;\n"
"}\n"
"\n"
"QTextBlock {\n"
"    margin-bottom: 10px; /* Отступ между блоками текста */\n"
"}\n"
"\n"
"/* Стили для QTableWidget */\n"
"QTableWidget {\n"
"    background-color: rgba(225, 225, 240, 150); /* Цвет фона с прозрачностью */\n"
"    border: 2px solid #aaa;\n"
"    border-radius: 7px;\n"
"    gridline-color: #ccc; /* Цвет сетки */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 8px; /* Внутренний отступ в ячейках */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #B4D5FF; /* Цвет выделенной ячейки */\n"
"    color: black;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #ddd; /* Цвет заголовка */\n"
"    border: 1px solid #aaa;\n"
"    padding: 6px; /* Внутренний отступ в заголовках */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #ddd; /* Цвет угловой кнопки */\n"
"    border: 1px solid #aaa;\n"
"}\n"
"\n"
"/* Стили для QPushButton */\n"
"QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #444444, stop:1 #222222); /* Градиент от серого к черному */\n"
"    color: white;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 7px;\n"
"    padding: 5px 10px;\n"
"    font: 75 10pt \"Courier\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #666666, stop:1 #444444); /* Градиент при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #222222, stop:1 #111111); /* Градиент при нажатии */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #777777; /* Серый цвет для отключенной кнопки */\n"
"    color: #aaaaaa;\n"
"}\n"
"")
        self.nameEdit = QtWidgets.QLineEdit(new_entry_db)
        self.nameEdit.setGeometry(QtCore.QRect(10, 42, 211, 20))
        self.nameEdit.setText("")
        self.nameEdit.setObjectName("nameEdit")
        self.nameLabel = QtWidgets.QLabel(new_entry_db)
        self.nameLabel.setGeometry(QtCore.QRect(10, 20, 211, 16))
        self.nameLabel.setObjectName("nameLabel")
        self.addB = QtWidgets.QPushButton(new_entry_db)
        self.addB.setEnabled(False)
        self.addB.setGeometry(QtCore.QRect(90, 210, 141, 23))
        self.addB.setObjectName("addB")
        self.backB = QtWidgets.QPushButton(new_entry_db)
        self.backB.setGeometry(QtCore.QRect(10, 210, 71, 23))
        self.backB.setObjectName("backB")
        self.countEdit = QtWidgets.QLineEdit(new_entry_db)
        self.countEdit.setGeometry(QtCore.QRect(10, 100, 211, 20))
        self.countEdit.setObjectName("countEdit")
        self.countLabel = QtWidgets.QLabel(new_entry_db)
        self.countLabel.setGeometry(QtCore.QRect(10, 70, 211, 16))
        self.countLabel.setObjectName("countLabel")
        self.PriceLabel = QtWidgets.QLabel(new_entry_db)
        self.PriceLabel.setGeometry(QtCore.QRect(10, 130, 211, 16))
        self.PriceLabel.setObjectName("PriceLabel")
        self.PriceEdit = QtWidgets.QLineEdit(new_entry_db)
        self.PriceEdit.setGeometry(QtCore.QRect(10, 160, 211, 20))
        self.PriceEdit.setObjectName("PriceEdit")

        self.retranslateUi(new_entry_db)
        QtCore.QMetaObject.connectSlotsByName(new_entry_db)

    def retranslateUi(self, new_entry_db):
        _translate = QtCore.QCoreApplication.translate
        new_entry_db.setWindowTitle(_translate("new_entry_db", "Додати криптовалюту"))
        self.nameLabel.setText(_translate("new_entry_db", "Назва (наприклад- BNBUSDT)"))
        self.addB.setText(_translate("new_entry_db", "Додати"))
        self.backB.setText(_translate("new_entry_db", "<Назад"))
        self.countLabel.setText(_translate("new_entry_db", "Кількість:"))
        self.PriceLabel.setText(_translate("new_entry_db", "Вартість:"))
