# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_binance.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 450)
        Form.setMinimumSize(QtCore.QSize(530, 450))
        Form.setMaximumSize(QtCore.QSize(550, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("main_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("/* Загальний стиль вікна */\n"
"QWidget {\n"
"    background-color: rgba(225, 225, 240, 150); /* Космічно-синій фон */\n"
"}\n"
"\n"
"/* Стили для QTextEdit */\n"
"QTextEdit {\n"
"    background-color: rgba(225, 225, 240, 150); /* Цвет фона с прозрачностью */\n"
"    color: #333;\n"
"    font: 75 10pt \"Courier\";\n"
"    margin: 10px; \n"
"    border: 2px solid #aaa; /* Граница QTextEdit */\n"
"    border-radius: 7px; /* Скругление углов */\n"
"    padding: 10px; /* Внутренний отступ */\n"
"}\n"
"\n"
"QTextEdit::selection {\n"
"    background-color: #B4D5FF; /* Цвет выделенного текста */\n"
"    color: black;\n"
"}\n"
"\n"
"QTextBlock {\n"
"    margin-bottom: 10px; /* Отступ между блоками текста */\n"
"}\n"
"\n"
"/* Стили для QTableWidget */\n"
"QTableWidget {\n"
"    background-color: rgba(225, 225, 240, 150); /* Цвет фона с прозрачностью */\n"
"    border: 2px solid #aaa;\n"
"    border-radius: 7px;\n"
"    gridline-color: #ccc; /* Цвет сетки */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 8px; /* Внутренний отступ в ячейках */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #B4D5FF; /* Цвет выделенной ячейки */\n"
"    color: black;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #ddd; /* Цвет заголовка */\n"
"    border: 1px solid #aaa;\n"
"    padding: 6px; /* Внутренний отступ в заголовках */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #ddd; /* Цвет угловой кнопки */\n"
"    border: 1px solid #aaa;\n"
"}\n"
"\n"
"/* Стили для QPushButton */\n"
"QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #444444, stop:1 #222222); /* Градиент от серого к черному */\n"
"    color: white;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 7px;\n"
"    padding: 5px 10px;\n"
"    font: 75 10pt \"Courier\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #666666, stop:1 #444444); /* Градиент при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #222222, stop:1 #111111); /* Градиент при нажатии */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #777777; /* Серый цвет для отключенной кнопки */\n"
"    color: #aaaaaa;\n"
"}\n"
"")
        self.refreshButton = QtWidgets.QPushButton(Form)
        self.refreshButton.setEnabled(False)
        self.refreshButton.setGeometry(QtCore.QRect(10, 390, 341, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("update_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon1)
        self.refreshButton.setIconSize(QtCore.QSize(30, 30))
        self.refreshButton.setObjectName("refreshButton")
        self.deleteDBButton = QtWidgets.QPushButton(Form)
        self.deleteDBButton.setEnabled(False)
        self.deleteDBButton.setGeometry(QtCore.QRect(360, 360, 81, 21))
        self.deleteDBButton.setObjectName("deleteDBButton")
        self.addDBButton = QtWidgets.QPushButton(Form)
        self.addDBButton.setGeometry(QtCore.QRect(460, 360, 81, 21))
        self.addDBButton.setObjectName("addDBButton")
        self.exitButton_4 = QtWidgets.QPushButton(Form)
        self.exitButton_4.setGeometry(QtCore.QRect(360, 390, 181, 51))
        self.exitButton_4.setObjectName("exitButton_4")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(360, 10, 181, 341))
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget_2 = QtWidgets.QTableWidget(Form)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 10, 341, 341))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("QHeaderView::section { background-color: transparent; \n"
"border: none;}")
        self.tableWidget_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(23)
        self.total_balance = QtWidgets.QLabel(Form)
        self.total_balance.setGeometry(QtCore.QRect(10, 350, 171, 16))
        self.total_balance.setStyleSheet("background-color:none")
        self.total_balance.setObjectName("total_balance")
        self.total_pnl = QtWidgets.QLabel(Form)
        self.total_pnl.setGeometry(QtCore.QRect(10, 370, 191, 16))
        self.total_pnl.setStyleSheet("background-color:none")
        self.total_pnl.setObjectName("total_pnl")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BinanceWidget"))
        self.refreshButton.setText(_translate("Form", "Оновити"))
        self.deleteDBButton.setText(_translate("Form", "-"))
        self.addDBButton.setText(_translate("Form", "+"))
        self.exitButton_4.setText(_translate("Form", "Вихід"))
        self.total_balance.setText(_translate("Form", "Ваш загальний баланс"))
        self.total_pnl.setText(_translate("Form", "Ваш загальний PNL"))
